too_many_cats-master/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:new, :create]
  post 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve', as: :approve
  post 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny', as: :deny
end

too_many_cats-master/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  CAT_COLORS = ["black", "white", "orange"]

  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: CAT_COLORS,
    message: "cat can only be black, white, or orange" }
  validates :sex, inclusion: { in: ["m", "f"],
    message: "cat has to be male or female" }

  belongs_to(
      :owner,
      class_name: "User",
      foreign_key: :user_id,
      primary_key: :id
    )

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  def age
    time_ago_in_words(birth_date)
  end
end

too_many_cats-master/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :logged_in_redirect
  before_action :verify_owner
  skip_before_action :verify_owner, only: [:index, :new, :show, :create]


  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

  def logged_in_redirect
    redirect_to new_session_url if current_user.nil?
  end

  def verify_owner
    @cat = Cat.find(params[:id])
    redirect_to cats_url unless @cat.user_id == current_user.id
  end


end

too_many_cats-master/app/helpers/cat_helper.rb
module CatHelper
end

too_many_cats-master/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "patch" : "post" %>
<% submit_text = cat.persisted? ? "Change cat" : "Create cat" %>

<form action="<%= action_url%>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">
  Name:
  <input type="text" name="cat[name]" value ="<%= @cat.name %>">
  Sex:
  <input type="radio" name="cat[sex]" id='cat_sex_female' value='f' <%= "checked" if @cat.sex == "f" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <input type="radio" name="cat[sex]" id="cat_sex_male" value="m" <%= "checked" if @cat.sex == "m" %>>
  <label for="cat_sex_male">Male</label>

  Color:
  <select name="cat[color]" id="color">

    <option <%= "selected" if @cat.color.nil? %> ></option>
    <option value="black" <%= "selected" if @cat.color == 'black' %> >Black</option>
    <option value="white" <%= "selected" if @cat.color == 'white' %> >White</option>
    <option value="orange" <%= "selected" if @cat.color == 'orange' %>>Orange</option>
  </select>

  Birth Date:
  <input type="date" name="cat[birth_date]" value = <%= @cat.birth_date %> >

  <textarea rows="4" cols="50" name="cat[description]"><%= @cat.description %></textarea>

  <input type="submit" value="<%= submit_text %>">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">
</form>

too_many_cats-master/app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

too_many_cats-master/app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <li><%= link_to cat.name, cat_url(cat.id) %></li>
<% end %>

too_many_cats-master/app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

too_many_cats-master/app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
    <th>Owner</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
    <td><%= @cat.owner.user_name %></td>
  </tr>
</table>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Requester</th>
    <th>Status</th>
  <tr>
  <% @cat.rental_requests.each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.requester.user_name %></td>
    <td><%= request.status %></td>
    <% if request.status == "PENDING" && current_user.id == request.owner.id %>
      <td><%= button_to("Approve", approve_url(request)) %></td>
      <td><%= button_to("Deny", deny_url(request)) %></td>
    <% end %>
  </tr>
  <% end %>
</table>